const fs = require('fs');
const path = require('path');
const { getPool, isPostgresConfigured } = require('./client');

/**
 * Migration runner.
 *
 * Reads .sql files from BOTH db/migrations/ (hand-authored read-model and
 * feature SQL, e.g. 009_playlists.sql) and db/drizzle/ (generated by
 * drizzle-kit in development or auto-generated at Docker build time) and
 * applies any that haven't been applied yet. Tracks applied migrations by
 * content hash in a __drizzle_migrations table.
 *
 * Both sources use IF NOT EXISTS guards, so overlapping coverage between a
 * hand-authored file and its Drizzle-generated counterpart is safe to apply.
 * Filenames recorded in the legacy schema_migrations table (pre-Drizzle
 * runner) are treated as applied without re-running.
 *
 * This uses the pg Pool directly rather than Drizzle ORM's built-in migrate()
 * function, which in drizzle-orm >= 0.45 has incompatibilities with raw SQL
 * migration files (see "table.primaryKey is not a function").
 */
function listSqlFiles(dir) {
  let files = [];
  try {
    files = fs.readdirSync(dir).filter((f) => f.endsWith('.sql')).sort();
  } catch {
    return [];
  }
  return files.map((file) => ({ dir, file, fullPath: path.join(dir, file) }));
}

/**
 * Ordered migration plan: hand-authored files first (001..009 carry the base
 * read-model tables), then Drizzle-generated files. Pure — safe to unit test.
 */
function collectMigrationFiles(baseDir = __dirname) {
  return [
    ...listSqlFiles(path.join(baseDir, 'migrations')),
    ...listSqlFiles(path.join(baseDir, 'drizzle')),
  ];
}

/** Simple stable hash for migration content (not cryptographic). */
function simpleHash(str) {
  let h = 0;
  for (let i = 0; i < str.length; i++) {
    const c = str.charCodeAt(i);
    h = ((h << 5) - h) + c;
    h = h & h; // Convert to 32-bit integer
  }
  return Math.abs(h).toString(16).padStart(8, '0');
}

async function isAlreadyApplied(pool, entry, hash) {
  const { rows } = await pool.query(
    'SELECT 1 FROM __drizzle_migrations WHERE hash = $1',
    [hash],
  );
  if (rows.length > 0) return true;
  // Legacy filename-based tracking from the pre-Drizzle runner.
  try {
    const legacy = await pool.query(
      'SELECT 1 FROM schema_migrations WHERE id = $1',
      [entry.file],
    );
    if (legacy.rowCount > 0) {
      await pool.query('INSERT INTO __drizzle_migrations (hash) VALUES ($1)', [hash]);
      return true;
    }
  } catch {
    // schema_migrations never existed on this database — ignore.
  }
  return false;
}

async function runMigrations() {
  if (!isPostgresConfigured()) {
    throw new Error('Postgres is not configured. Set POSTGRES_HOST, POSTGRES_DB, and POSTGRES_USER.');
  }

  const entries = collectMigrationFiles(__dirname);

  if (entries.length === 0) {
    console.log('[db:migrate] No migration files found in db/migrations/ or db/drizzle/');
    return;
  }

  const pool = getPool();
  if (!pool) {
    throw new Error('Failed to create database pool.');
  }

  // Ensure the tracking table exists
  await pool.query(`
    CREATE TABLE IF NOT EXISTS __drizzle_migrations (
      id SERIAL PRIMARY KEY,
      hash TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `);

  for (const entry of entries) {
    // Compute content hash
    const sql = fs.readFileSync(entry.fullPath, 'utf8');
    const hash = simpleHash(sql);

    // Check if already applied
    if (await isAlreadyApplied(pool, entry, hash)) {
      console.log(`[db:migrate] Already applied: ${entry.file} (hash: ${hash.slice(0, 12)}...)`);
      continue;
    }

    // Apply migration
    await pool.query('BEGIN');
    try {
      await pool.query(sql);
      await pool.query(
        'INSERT INTO __drizzle_migrations (hash) VALUES ($1)',
        [hash],
      );
      await pool.query('COMMIT');
      console.log(`[db:migrate] Applied ${entry.file} (hash: ${hash.slice(0, 12)}...)`);
    } catch (err) {
      await pool.query('ROLLBACK');
      console.error(`[db:migrate] Failed to apply ${entry.file}:`, err.message);
      throw err;
    }
  }
}

if (require.main === module) {
  runMigrations()
    .then(() => {
      console.log('[db:migrate] Complete');
      process.exit(0);
    })
    .catch((err) => {
      console.error('[db:migrate] Failed:', err.message);
      process.exit(1);
    });
}

module.exports = { runMigrations, collectMigrationFiles, simpleHash, isAlreadyApplied };
